apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  selector:
    matchLabels:
  replicas: 1
  template:
    metadata:
      labels:
    spec:
      serviceAccountName: operator
      containers:
        - command:
            - /manager
          args:
            - "--leader-elect"
            - "--health-probe-bind-address=:8081"
            - "--metrics-bind-address=:8080"
            - "--log-level=info"
            - "--log-encoder=json"
          image: controller:latest
          name: manager
          ports:
          - containerPort: 8080
            name: dry-run
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          imagePullPolicy: Never
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: OPERATOR_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-atlas-operator
  namespace: mongodb-atlas-operator
spec:
  ports:
    - name: dry-run
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
  sessionAffinity: None
  type: ClusterIP
